### ISSUE TITLE
ios系统quantumult和quantumultX导入js文件显示错误

### ISSUE THREAD

**Issue by simple66666** [Milky01/wozaixiaoyuan#5]
配置文件并未包含标识[server]

**Comment by simple66666** [comment]
文件名是ask4leave

**Comment by simple66666** [comment]
quantumultX导入配置文件提示无效配置文件-导入   配置文件语法错误，line 1,date.prototype.format=function(fmt){

**Comment by GFB214** [comment]
那是导入配置文件..不是导入js脚本

**Comment by chabei666** [comment]
楼主会使用没有，可以请教一下怎么用吗

**Comment by simple66666** [comment]
很遗憾告诉你，我还是没有学会使用thor，直到我开始使用安卓设备了

**Comment by chabei666** [comment]
> 很遗憾告诉你，我还是没有学会使用thor，直到我开始使用安卓设备了

安卓设备有办法修改请假吗

**Comment by simple66666** [comment]
很显然，得益于安卓设备的开放型和简易性，我们能够很容易的得到可用的假条。

**Comment by chabei666** [comment]
如果你能将方法告诉我请教一下那将会非常美好

**Comment by GFB214** [comment]
httpcanary> 很遗憾告诉你，我还是没有学会使用thor，直到我开始使用安卓设备了

**Comment by GFB214** [comment]
http canary> > 很遗憾告诉你，我还是没有学会使用thor，直到我开始使用安卓设备了
> 
> 
> 
> 安卓设备有办法修改请假吗

**Comment by simple66666** [comment]
好

**Comment by simple66666** [comment]
记得安装谷歌框架> 如果你能将方法告诉我请教一下那将会非常美好

**Comment by chabei666** [comment]
> 记得安装谷歌框架> 如果你能将方法告诉我请教一下那将会非常美好

如果可以添加我的qq599554050那将会很非常感谢你
